# Generated by Django 5.2.11 on 2026-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('macbooks', 'MacBooks'), ('iphones', 'iPhones'), ('ipads', 'iPads'), ('watch', 'Apple Watch'), ('airpods', 'AirPods'), ('accessories', 'Accessories')], max_length=20),
        ),
    ]
